### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by yyfastow** [yyfastow/EletricBikeReserving#1]
# TODO:
### Bike models
- [x] make new variable that takes the amount of preorders made.
- [x] make a variable that tells how much preorders needed to send bikes
- [x]  show user how much preorders needed, to send, how much order exist.
- [x] show how much more orders are needed
- [x] allow pictures to show of bikes
- [ ] add specs to bikes
### Orders
- [x] make a model for orders so user could edit it.
- [x] change it so user logs in to make order or signs up by filling out form
- [x] allow user to put in credit card information
- [x] divide template to show
- [x] make a cart that saves orders in cart so you could order many items at once
  - [x] user could see all item in shopping cart and remove them.
- [x] order more then one item at once
### Admin
- [x] allow admin to sign in and see all orders and all costumers information.
- [x] tell admin when are preorders are complete to there number So he could ship
- [x] allow admin to mark as "Shipped" when he ships it.
- [ ] charge the person credit card. (maybe skip)
### User Account
- [x] allow users to log in there account.
- [x] make user account to show all orders from that account.
- [x] if he orders more then one item only show that item
- [x] Make a page for editing orders
  - [x] allow users to change credit card or address after her reserves
- [x] Canceling Orders
- [x] Allow user to see all of there orders only if they are logged in.
- [x] Send all message that item is being sent
  - [x] tell user how much he was charged
  - [x] tell user when item is ready to be shipped on main page
  - [x] don't let user cancel an order that ready to ship.
- [x] Every email, and username be unique
  - [ ] when make account user should log in automatically
### Messaging
- [x] On main page show all messages send to user by admin in logged in
- [ ] Send an email any time you send a message
- [x] Admin could send messages to user on main page
- [x] user logged in or not could send message to admin (if not logged in shown as Anonymous)
- [x] cant message someone not logged in
- [x] Admin sees on main page all messages by users
  - [x] Link on each name to user page

### Styles
- [ ] peek footer on buttom of page
- [ ] fix all cases of 2 rows to either be one row or collapse into 1 row when brought down to tablet size
